layout_spectrum: 0.7988550979386794
typography_spectrum: 0.6052546576416986
color:
  lightness: 0.7829961023696395
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  saturation: 0.030749094128184537
  brandStrength: 0.9729596174412435
  rhythmicContrast: 0.022701583726442244
name: FDP Communications
analytics: {}
purpose:
  - type: contact
    url: 'tel:+639175260244'
    label: Call us +639175260244
  - type: contact
    url: 'mailto:fdpcommunication@gmail.com'
    label: Email us
github: true
description: Crafting Stories that Matter
author:
  name: Dan Pascual
  email: fdpcommunication@gmail.com
cta:
  bucket: null
  version: null
  domain: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c911b3c-a8e9-4116-889b-2bcd1b2f3bdd.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7c911b3c-a8e9-4116-889b-2bcd1b2f3bdd.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
content_rating:
  adult: false
opengraph: {}
title: FDP Communications
url: 'http://fdpcommunication.com/'
