layout_spectrum: 0.5483871
typography_spectrum: 0.9247312
color:
  saturation: 0.7150537
  lightness: 0.718638
  brandStrength: 1
  rhythmicContrast: 0.7240143
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: FDPCommunications
