name: FDP Communications
analytics:
  google: UA-64070424-1
purpose: []
github: true
description: 'Of Insights, Ideas, Stories & Lessons'
author:
  name: Danny Pascual
  email: fdpcommunication@gmail.com
cta:
  bucket: null
  version: null
  domain: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.05555556
color:
  lightness: 0.5232975
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  saturation: 0.5232975
  brandStrength: 1
  rhythmicContrast: 0.5376344
content_rating:
  adult: false
typography_spectrum: 0.9247312
opengraph: {}
title: FDP Communications
